"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import story as shared_story
from typing import Optional



@dataclasses.dataclass
class GetItemRequest:
    item_id: int = dataclasses.field(metadata={'path_param': { 'field_name': 'item_id', 'style': 'simple', 'explode': False }})
    r"""Numeric ID of the item to get"""
    




@dataclasses.dataclass
class GetItemResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    story: Optional[shared_story.Story] = dataclasses.field(default=None)
    r"""Successful operation"""
    

