"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import Optional



@dataclasses.dataclass
class GetStoriesResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    get_stories_200_application_json_integers: Optional[list[int]] = dataclasses.field(default=None)
    r"""Ok"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

